-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- SINCRO: 2026-03-22 06:00 (Sincronización Total Maestro 🛡️ - Cascades & Unique Constraints)

CREATE TABLE public.account_mapping_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  context text NOT NULL,
  account_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT account_mapping_rules_pkey PRIMARY KEY (id),
  CONSTRAINT account_mapping_rules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT account_mapping_rules_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  account_type text DEFAULT 'corriente'::text,
  currency text DEFAULT 'CLP'::text,
  chart_account_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_accounts_chart_account_id_fkey FOREIGN KEY (chart_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.bank_mapping_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  search_pattern text NOT NULL,
  target_account_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_mapping_rules_pkey PRIMARY KEY (id),
  CONSTRAINT bank_mapping_rules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_mapping_rules_target_account_id_fkey FOREIGN KEY (target_account_id) REFERENCES public.chart_of_accounts(id)
);
CREATE TABLE public.bank_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_line_id uuid UNIQUE,
  journal_entry_line_id uuid NOT NULL UNIQUE,
  match_type text DEFAULT 'manual'::text CHECK (match_type = ANY (ARRAY['manual'::text, 'automatic'::text, 'ai_suggested'::text])),
  confidence_score double precision DEFAULT 1.0,
  reconciled_at timestamp with time zone DEFAULT now(),
  reconciled_by uuid,
  status text DEFAULT 'reconciled'::text,
  notes text,
  organization_id uuid,
  CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT bank_reconciliations_bank_line_id_fkey FOREIGN KEY (bank_line_id) REFERENCES public.bank_statement_lines(id),
  CONSTRAINT bank_reconciliations_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES auth.users(id),
  CONSTRAINT bank_reconciliations_journal_entry_line_id_fkey FOREIGN KEY (journal_entry_line_id) REFERENCES public.journal_entry_lines(id),
  CONSTRAINT bank_reconciliations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.bank_statement_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  statement_id uuid,
  bank_account_id uuid NOT NULL,
  fecha date NOT NULL,
  descripcion text NOT NULL,
  monto bigint NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['cargo'::text, 'abono'::text])),
  referencia_bancaria text,
  rut_tercero text,
  is_reconciled boolean DEFAULT false,
  external_id text,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT bank_statement_lines_pkey PRIMARY KEY (id),
  CONSTRAINT bank_statement_lines_statement_id_fkey FOREIGN KEY (statement_id) REFERENCES public.bank_statements(id),
  CONSTRAINT bank_statement_lines_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_statement_lines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.bank_statements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid NOT NULL,
  period date NOT NULL,
  file_name text,
  original_balance bigint DEFAULT 0,
  final_balance bigint DEFAULT 0,
  status text DEFAULT 'processed'::text CHECK (status = ANY (ARRAY['pending'::text, 'processed'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bank_statements_pkey PRIMARY KEY (id),
  CONSTRAINT bank_statements_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id)
);
CREATE TABLE public.centralized_account_config (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  module_name character varying NOT NULL,
  transaction_type character varying NOT NULL,
  display_name character varying NOT NULL,
  tax_account_code character varying NOT NULL,
  tax_account_name character varying NOT NULL,
  revenue_account_code character varying NOT NULL,
  revenue_account_name character varying NOT NULL,
  asset_account_code character varying NOT NULL,
  asset_account_name character varying NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT centralized_account_config_pkey PRIMARY KEY (id),
  CONSTRAINT centralized_account_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  codigo character varying NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  nivel integer NOT NULL CHECK (nivel >= 1 AND nivel <= 4),
  parent_codigo character varying,
  tipo text NOT NULL,
  naturaleza text NOT NULL DEFAULT 'deudora'::text,
  acepta_movimiento boolean DEFAULT true,
  activo boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT chart_of_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.economic_indicators (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  codigo character varying NOT NULL UNIQUE,
  nombre text NOT NULL,
  valor numeric NOT NULL,
  fecha date NOT NULL,
  fuente text DEFAULT 'mindicador.cl'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT economic_indicators_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  tipo USER-DEFINED NOT NULL,
  titulo text NOT NULL,
  file_url text NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_documents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_terminations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL UNIQUE,
  fecha_inicio date NOT NULL,
  fecha_termino date NOT NULL,
  causal_despido text NOT NULL,
  vacaciones_pendientes_dias numeric DEFAULT 0,
  monto_vacaciones bigint DEFAULT 0,
  monto_indemnizacion_anos bigint DEFAULT 0,
  monto_mes_aviso bigint DEFAULT 0,
  total_finiquito bigint NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'borrador'::liquidation_status,
  pdf_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  worked_days_last_month integer DEFAULT 0,
  pending_salary_amount bigint DEFAULT 0,
  total_vacation_days_earned numeric DEFAULT 0,
  vacation_days_taken numeric DEFAULT 0,
  vacation_daily_rate bigint DEFAULT 0,
  proportional_vacation_days numeric DEFAULT 0,
  proportional_vacation_amount bigint DEFAULT 0,
  severance_years_service numeric DEFAULT 0,
  severance_monthly_salary bigint DEFAULT 0,
  notice_indemnification_amount bigint DEFAULT 0,
  christmas_bonus_amount bigint DEFAULT 0,
  other_bonuses_amount bigint DEFAULT 0,
  pending_overtime_amount bigint DEFAULT 0,
  CONSTRAINT employee_terminations_pkey PRIMARY KEY (id),
  CONSTRAINT employee_terminations_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_terminations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  rut character varying NOT NULL,
  nombres text NOT NULL,
  apellido_paterno text NOT NULL,
  apellido_materno text,
  fecha_ingreso date NOT NULL,
  fecha_termino date,
  cargo text,
  departamento text,
  tipo_contrato USER-DEFINED NOT NULL DEFAULT 'indefinido'::contract_type,
  sueldo_base bigint NOT NULL,
  gratificacion_legal boolean NOT NULL DEFAULT true,
  afp text,
  prevision_salud text,
  monto_isapre bigint DEFAULT 0,
  activo boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  descripcion_cargo text,
  birth_date date,
  address text,
  city character varying,
  region character varying,
  family_allowances integer DEFAULT 0,
  afc_active boolean DEFAULT true,
  email character varying,
  phone character varying,
  sexo character varying,
  estado_civil character varying,
  nacionalidad character varying DEFAULT 'Chilena'::character varying,
  horas_semanales integer DEFAULT 42,
  horario_detalle text,
  asignacion_colacion bigint DEFAULT 0,
  asignacion_movilizacion bigint DEFAULT 0,
  bono_fijo bigint DEFAULT 0,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.employment_contracts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  tipo_documento text NOT NULL DEFAULT 'contrato'::text,
  tipo_contrato text NOT NULL DEFAULT 'indefinido'::text,
  fecha_inicio date NOT NULL,
  fecha_termino_fijo date,
  sueldo_base bigint NOT NULL,
  cargo text NOT NULL,
  jornada_horas integer DEFAULT 42,
  gratificacion_tipo text DEFAULT 'legal'::text,
  lugar_trabajo text,
  descripcion_cargo text,
  status text NOT NULL DEFAULT 'borrador'::text,
  pdf_url text,
  firma_empleado_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer DEFAULT 1,
  parent_contract_id uuid,
  CONSTRAINT employment_contracts_pkey PRIMARY KEY (id),
  CONSTRAINT employment_contracts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employment_contracts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employment_contracts_parent_contract_id_fkey FOREIGN KEY (parent_contract_id) REFERENCES public.employment_contracts(id)
);
CREATE TABLE public.f29_box_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  f29_id uuid,
  box_code integer NOT NULL,
  description text,
  value numeric NOT NULL,
  box_type text DEFAULT 'determinativo'::text,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT f29_box_details_pkey PRIMARY KEY (id),
  CONSTRAINT f29_box_details_f29_id_fkey FOREIGN KEY (f29_id) REFERENCES public.f29_forms(id) ON DELETE CASCADE,
  CONSTRAINT f29_box_details_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.f29_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  periodo date NOT NULL,
  debito_fiscal bigint DEFAULT 0,
  credito_fiscal bigint DEFAULT 0,
  iva_determinado bigint DEFAULT 0,
  iva_a_pagar bigint DEFAULT 0,
  ppm_neto bigint DEFAULT 0,
  ppm_tasa numeric DEFAULT 0,
  retencion_honorarios bigint DEFAULT 0,
  total_a_pagar bigint DEFAULT 0,
  total_a_favor bigint DEFAULT 0,
  storage_path text,
  extraction_method text DEFAULT 'pdfplumber'::text,
  extraction_confidence numeric,
  parsed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ventas_netas bigint DEFAULT 0,
  prestamo_solidario bigint DEFAULT 0,
  CONSTRAINT f29_forms_pkey PRIMARY KEY (id),
  CONSTRAINT f29_forms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.fixed_assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  numero_serie text,
  fecha_adquisicion date NOT NULL,
  valor_adquisicion bigint NOT NULL,
  vida_util_meses integer NOT NULL,
  valor_residual bigint DEFAULT 0,
  metodo_depreciacion USER-DEFINED NOT NULL DEFAULT 'lineal'::depreciation_method,
  condicion USER-DEFINED NOT NULL DEFAULT 'activo'::asset_condition,
  depreciacion_mensual bigint DEFAULT 0,
  depreciacion_acumulada bigint DEFAULT 0,
  valor_libro_actual bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ultimo_periodo_depreciado date,
  CONSTRAINT fixed_assets_pkey PRIMARY KEY (id),
  CONSTRAINT fixed_assets_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  fecha date NOT NULL,
  glosa text NOT NULL,
  numero_asiento integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.journal_entry_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entry_id uuid NOT NULL,
  cuenta_codigo character varying NOT NULL,
  cuenta_nombre text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['debe'::text, 'haber'::text])),
  monto bigint NOT NULL CHECK (monto > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  account_id uuid,
  organization_id uuid,
  CONSTRAINT journal_entry_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entry_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT journal_entry_lines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.liquidations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  periodo date NOT NULL,
  sueldo_base bigint NOT NULL,
  horas_extra bigint DEFAULT 0,
  bono_colacion bigint DEFAULT 0,
  bono_movilizacion bigint DEFAULT 0,
  otros_haberes bigint DEFAULT 0,
  total_haberes_brutos bigint NOT NULL,
  afp bigint DEFAULT 0,
  sis bigint DEFAULT 0,
  salud bigint DEFAULT 0,
  afc_trabajador bigint DEFAULT 0,
  impuesto_unico bigint DEFAULT 0,
  otros_descuentos bigint DEFAULT 0,
  total_descuentos bigint NOT NULL,
  sueldo_liquido bigint NOT NULL,
  afc_empresa bigint DEFAULT 0,
  seguro_invalidez bigint DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'borrador'::liquidation_status,
  pdf_url text,
  generated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  calculation_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  account_id_neto uuid,
  gratificacion bigint DEFAULT 0,
  asignacion_colacion bigint DEFAULT 0,
  asignacion_movilizacion bigint DEFAULT 0,
  horas_extra_monto bigint DEFAULT 0,
  base_imponible_afp bigint DEFAULT 0,
  base_imponible_salud bigint DEFAULT 0,
  base_imponible_impuesto bigint DEFAULT 0,
  afp_comision bigint DEFAULT 0,
  sis_empresa bigint DEFAULT 0,
  afp_code character varying DEFAULT ''::character varying,
  salud_code character varying DEFAULT ''::character varying,
  uf_valor_usado numeric DEFAULT 0,
  dias_trabajados integer DEFAULT 30,
  asignacion_familiar bigint DEFAULT 0,
  bono_extra bigint DEFAULT 0,
  folio_number text NOT NULL,
  CONSTRAINT liquidations_pkey PRIMARY KEY (id),
  CONSTRAINT liquidations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT liquidations_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
  CONSTRAINT liquidations_account_id_neto_fkey FOREIGN KEY (account_id_neto) REFERENCES public.chart_of_accounts(id),
  CONSTRAINT unique_employee_period_org UNIQUE (organization_id, employee_id, periodo)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'viewer'::member_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  permissions jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
CREATE TABLE public.organization_payroll_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL UNIQUE,
  afp_configs jsonb NOT NULL DEFAULT '[]'::jsonb,
  health_configs jsonb NOT NULL DEFAULT '[]'::jsonb,
  uf_tope_afp numeric DEFAULT 87.8,
  uf_tope_salud numeric DEFAULT 83.3,
  sueldo_minimo bigint DEFAULT 529000,
  limite_asignacion_familiar bigint DEFAULT 1000000,
  asignacion_tramo_a bigint DEFAULT 13596,
  asignacion_tramo_b bigint DEFAULT 8397,
  asignacion_tramo_c bigint DEFAULT 2798,
  afc_indefinido_trabajador_pct numeric DEFAULT 0.6,
  afc_indefinido_empresa_pct numeric DEFAULT 2.4,
  afc_fijo_empresa_pct numeric DEFAULT 3.0,
  mutual_code character varying DEFAULT 'ACHS'::character varying,
  caja_compensacion_code character varying DEFAULT ''::character varying,
  rep_legal_nombre text DEFAULT ''::text,
  rep_legal_rut character varying DEFAULT ''::character varying,
  rep_legal_cargo text DEFAULT 'GERENTE GENERAL'::text,
  last_previred_sync timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_payroll_settings_pkey PRIMARY KEY (id),
  CONSTRAINT organization_payroll_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rut_empresa character varying NOT NULL UNIQUE,
  nombre text NOT NULL,
  giro text,
  direccion text,
  comuna text,
  region text,
  email text,
  telefono character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payroll_book_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  payroll_book_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  employee_rut text NOT NULL,
  apellido_paterno text,
  apellido_materno text,
  nombres text,
  cargo text,
  area text,
  centro_costo text,
  dias_trabajados integer DEFAULT 30,
  horas_semanales integer DEFAULT 45,
  horas_no_trabajadas integer DEFAULT 0,
  sueldo_base bigint DEFAULT 0,
  gratificacion_legal bigint DEFAULT 0,
  promedio_variable_vacaciones bigint DEFAULT 0,
  colacion bigint DEFAULT 0,
  movilizacion bigint DEFAULT 0,
  asignacion_familiar bigint DEFAULT 0,
  total_haberes_imponibles bigint DEFAULT 0,
  total_haberes_brutos bigint DEFAULT 0,
  descuento_afp bigint DEFAULT 0,
  descuento_salud bigint DEFAULT 0,
  descuento_afc bigint DEFAULT 0,
  impuesto_unico bigint DEFAULT 0,
  otros_descuentos bigint DEFAULT 0,
  total_descuentos bigint DEFAULT 0,
  sueldo_liquido bigint DEFAULT 0,
  CONSTRAINT payroll_book_details_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_book_details_payroll_book_id_fkey FOREIGN KEY (payroll_book_id) REFERENCES public.payroll_books(id) ON DELETE CASCADE,
  CONSTRAINT payroll_book_details_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);
CREATE TABLE public.payroll_books (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  periodo date NOT NULL,
  book_number integer NOT NULL,
  company_name text NOT NULL,
  company_rut text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  total_employees integer DEFAULT 0,
  total_haberes bigint DEFAULT 0,
  total_descuentos bigint DEFAULT 0,
  total_liquido bigint DEFAULT 0,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_books_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_books_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  avatar_url text,
  preferences jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
CREATE TABLE public.purchase_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  periodo date NOT NULL,
  tipo_documento USER-DEFINED NOT NULL,
  folio bigint NOT NULL,
  rut_emisor character varying NOT NULL,
  razon_social_emisor text,
  fecha_docto date NOT NULL,
  monto_neto bigint DEFAULT 0,
  monto_exento bigint DEFAULT 0,
  monto_iva bigint DEFAULT 0,
  monto_total bigint NOT NULL,
  journal_entry_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  monto_calculado bigint DEFAULT 0,
  es_suma boolean DEFAULT true,
  import_id uuid,
  CONSTRAINT purchase_records_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_records_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL,
  CONSTRAINT purchase_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.rcv_imports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  periodo date NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['purchases'::text, 'sales'::text])),
  file_name text NOT NULL,
  storage_path text NOT NULL,
  total_docs integer DEFAULT 0,
  failed_docs integer DEFAULT 0,
  error_log jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rcv_imports_pkey PRIMARY KEY (id),
  CONSTRAINT rcv_imports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.regional_news (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL UNIQUE,
  category text NOT NULL,
  content text NOT NULL,
  image_url text,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source_url text UNIQUE,
  source_name text,
  normalized_title text,
  summary text,
  slug text NOT NULL UNIQUE,
  CONSTRAINT regional_news_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  periodo date NOT NULL,
  tipo_documento USER-DEFINED NOT NULL,
  folio bigint NOT NULL,
  rut_receptor character varying NOT NULL,
  razon_social_receptor text,
  fecha_docto date NOT NULL,
  monto_neto bigint DEFAULT 0,
  monto_exento bigint DEFAULT 0,
  monto_iva bigint DEFAULT 0,
  monto_total bigint NOT NULL,
  journal_entry_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  monto_calculado bigint DEFAULT 0,
  es_suma boolean DEFAULT true,
  import_id uuid,
  CONSTRAINT sales_records_pkey PRIMARY KEY (id),
  CONSTRAINT sales_records_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL,
  CONSTRAINT sales_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.termination_causes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  article_code character varying NOT NULL UNIQUE,
  article_name character varying NOT NULL,
  description text NOT NULL,
  requires_notice boolean NOT NULL DEFAULT false,
  notice_days integer DEFAULT 0,
  requires_severance boolean NOT NULL DEFAULT false,
  severance_calculation_type character varying,
  is_with_just_cause boolean NOT NULL DEFAULT false,
  category character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT termination_causes_pkey PRIMARY KEY (id)
);
